import Head from 'next/head';

import Header from './components/header';
import Main from './components/main';
import Footer from './components/footer';
import Motion from './components/motion';
import Load from './components/load';
import { useEffect, useState } from 'react';

export default function Home() {
  const [load, setLoad] = useState(false);

  // useEffect(() => {
  //   setTimeout(() => {
  //     setLoad(true)
  //   }, 2000)
  // },[])

  return (
    <>
      <Head>
        <title>Web制作Monkey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!load && <Load />}
      {load && (
        <>
          <Header />
          <Motion>
            <Main />
          </Motion>
          <Footer />
        </>
      )}
    </>
  );
}
